spring:
  application:
    name: pricing-service

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

    #  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:./data/bookdb
    #    username: sa
    #    password: 
        
  datasource:
    url: jdbc:postgresql://localhost:5433/pricing
    username: postgres
    password: jboss
    driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: secret123
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://auth-server:7001/oauth2/jwks

  kafka:
    bootstrap-servers:  # leave empty or comment out
      admin:
      fail-fast: false

server:
  port: 8082
  address: 0.0.0.0

  error:
    path: /error2

management:
  endpoints:
    web:
      exposure:
        include: health,info,threaddump,mappings,metrics,prometheus
  endpoint:
    threaddump:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

